### ISSUE TITLE
Heavy motion blur sometimes occurs

### ISSUE THREAD

**Issue by ian-wevr** [googlevr/gvr-android-sdk#470] opened 2017-08-30 02:36 UTC
I have an application targeting the 1.40 SDK that has worked as expected for some time. At some point I started noticing a heavy motion blur post process effect would sometimes be applied. Sometimes I can start and the effect isn't there, and then I can restart and it is.

My application does not have any logic for motion blur. What could be causing this, or how might I be sporadically enabling this with code that previously appeared to work as expected?

**Comment by fredsa** [comment] 2017-08-30 03:35
Can you compare what you're seeing when this Android setting is applied?
**Settings > Display > Advanced > When device is in VR: Reduce flicker**

**Comment by jdduke** [comment] 2017-08-30 17:23
Thanks for the feedback @ian-wevr. If you could capture a bug report or the logcat when you observe this issue, that would be helpful. Also, what device and (exact) Android version/build are you using? It's possible this was an issue that has since been fixed in Android Oreo.

**Comment by ian-wevr** [comment] 2017-08-31 03:38
Thanks for your responses.

@jdduke 
> Android version/build are you using?

7.1.2 / NJH47D

> If you could capture a bug report or the logcat when you observe this issue, that would be helpful.

I should be able to get to this tomorrow (8/31).

@fredsa 
> Can you compare what you're seeing with what you get when this Android setting is applied?

I'll see if I can find a way to compare tomorrow (8/31) -- the problem is intermittent, so it's difficult to avoid false negatives.

**Comment by jdduke** [comment] 2017-08-31 18:05
Yeah, this appears to be a regression in Android in N MR2 (7.1.2), which has since been fixed on Android O. Thanks for flagging, I'll go ahead and close this as the only permanent solution here would be to upgrade to O.

**Closed by jdduke** 2017-08-31 18:05 UTC
