### ISSUE TITLE
Failure to Install No Matching ABIs

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#131] opened 2016-06-27 20:37 UTC
Hi guys, 
I wanted to do compatibility testing using emulators.  My default emulator was a Nexus5 skin with GPU accel enabled (intel architecture).  I kept trying to install onto the emulator and got the following error:
```
06/27 16:27:49: Launching reader
$ adb push /Users/Nakhimovich/android-phoenix/reader/build/outputs/apk/reader-google-debug.apk /data/local/tmp/com.nytimes.android.debug
$ adb shell pm install -r "/data/local/tmp/com.nytimes.android.debug"
	pkg: /data/local/tmp/com.nytimes.android.debug
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]


$ adb shell pm uninstall com.nytimes.android.debug
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK
```
Google seems to suggest that this problem exists when Native libraries are not included for an architecture. Could this be the case or just an emulation problem?  Thank you kindly.

**Comment by sigmaxipi** [comment] 2016-06-27 22:47
The SDK only ships 32-bit ARM libraries in the .aars. If you want to run on x86 emulators, you need to follow the directions at https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native

**Comment by digitalbuddha** [comment] 2016-06-27 22:51
What about for prod release will there be 2 versions or do we need to recompile ourselves?

**Comment by sigmaxipi** [comment] 2016-06-28 01:50
We're planning on reworking the .aar distribution system as part of https://github.com/googlevr/gvr-android-sdk/issues/114 and this will streamline alternative architectures of the GVR SDK. But until that is ready, you will need to configure custom build steps for your app.

**Comment by dav-cz** [comment] 2016-07-07 01:43
Marking this a duplicate of https://github.com/googlevr/gvr-android-sdk/issues/38

**Closed by dav-cz** 2016-07-07 01:43 UTC
