### ISSUE TITLE
Google Vr Video View Error

### ISSUE THREAD

**Issue by Sabinay-android** [googlevr/gvr-android-sdk#163] opened 2016-07-16 12:32 UTC
after videoWidgetView.loadVideo(Uri.parse("http://192.168.0.115:8888/googlemap/MageComp.mp4"));
or
videoWidgetView..loadVideoFromAsset("3dtest3.mp4");
// 3dtest3.mp4 stored in my asset forlder

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.vr.sdk.widgets.video.VideoTexture.getIsTextureSet()' on a null object reference
at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.prepareFrame(VrVideoPlayerInternal.java:318)
at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(VrVideoRenderer.java:57)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1566)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by dav-cz** [comment] 2016-07-21 17:25
This is a duplicate of 
https://github.com/googlevr/gvr-android-sdk/issues/145

**Closed by dav-cz** 2016-07-21 17:25 UTC
