### ISSUE TITLE
Videowidget conflicts with Exoplayer library

### ISSUE THREAD

**Issue by hegazy** [googlevr/gvr-android-sdk#147] opened 2016-07-06 22:56 UTC
I'm using ExoPlayer in my app and you also include it inside the videowidget AAR and this result in an error when generating an APK. 

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForProdRelease'.> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/exoplayer/AspectRatioFrameLayout.class
```

If I removed the Exoplyer dependency from gradle, it works but I can't depend on that.

The question is why you don't add it as a dependency that we can exclude with our own version of exoplayer?

**Comment by dav-cz** [comment] 2016-07-07 01:37
Thanks for the reminder. Marking this as a duplicate of https://github.com/googlevr/gvr-android-sdk/issues/81, as it's the same underlying problem (deps are baked in when they shouldn't).

**Closed by dav-cz** 2016-07-07 01:37 UTC

**Comment by clarle** [comment] 2017-01-20 02:48
@dav-cz This issue is still happening - do you think it'll be removed anytime?

Thanks!
