### ISSUE TITLE
samples-sdk-videoplayer crash

### ISSUE THREAD

**Issue by dkshin** [googlevr/gvr-android-sdk#546] opened 2018-03-26 04:41 UTC
03-26 12:10:45.701 32463-32490/com.google.vr.sdk.samples.videoplayer A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1000010b8 in tid 32490 (GLThread 4806), pid 32463 (les.videoplayer)
03-26 12:10:45.801 32506-32506/? I/crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-26 12:10:45.805 588-588/? I//system/bin/tombstoned: received crash request for pid 32463
03-26 12:10:45.808 32506-32506/? I/crash_dump64: performing dump of process 32463 (target tid = 32490)
03-26 12:10:45.808 32506-32506/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-26 12:10:45.808 32506-32506/? A/DEBUG: Build fingerprint: 'google/bullhead/bullhead:8.1.0/OPM3.171019.016/4565142:user/release-keys'
03-26 12:10:45.809 32506-32506/? A/DEBUG: Revision: 'rev_1.0'
03-26 12:10:45.809 32506-32506/? A/DEBUG: ABI: 'arm64'
03-26 12:10:45.809 32506-32506/? A/DEBUG: pid: 32463, tid: 32490, name: GLThread 4806  >>> com.google.vr.sdk.samples.videoplayer <<<
03-26 12:10:45.809 32506-32506/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1000010b8
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x0   0000007b3c7d4400  x1   0000000000000000  x2   0000000000000000  x3   0000007b3c5a7180
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x4   0000007b48ec74a8  x5   0000007b3c5a71f8  x6   0000007bd89ff000  x7   0000000000000000
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x8   0000000100001080  x9   0000007b48ec74a8  x10  1ffffffffffffff8  x11  0000007b3b905000
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x12  0000000000000000  x13  ffffffffa549f3f8  x14  002150f372000000  x15  003b9aca00000000
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x16  0000007b3dedd580  x17  0000007bd7dbd470  x18  0000000000000000  x19  0000007b3b82d918
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x20  00000000ffffffff  x21  0000007b53e4e500  x22  ffffffffffffffff  x23  0000007b53e4e8d0
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x24  ffffffffffffffff  x25  0000007b48ec7390  x26  0000007b3b82cdc0  x27  0000007b3c5a5e80
03-26 12:10:45.809 32506-32506/? A/DEBUG:     x28  0000007b3c5a60e0  x29  0000000000000001  x30  0000007b3dcaca04
03-26 12:10:45.809 32506-32506/? A/DEBUG:     sp   0000007b3d35d760  pc   0000007b3dcacad0  pstate 0000000060000000
03-26 12:10:45.813 32506-32506/? A/DEBUG: backtrace:
03-26 12:10:45.813 32506-32506/? A/DEBUG:     #00 pc 0000000000057ad0  /data/app/com.google.vr.sdk.samples.videoplayer-jBcNucAD5O9zNL7Fr-Fkeg==/lib/arm64/libgvr.so
03-26 12:10:45.813 32506-32506/? A/DEBUG:     #01 pc 000000000004cb90  /data/app/com.google.vr.sdk.samples.videoplayer-jBcNucAD5O9zNL7Fr-Fkeg==/lib/arm64/libgvr.so (gvr_frame_submit+480)
03-26 12:10:45.813 32506-32506/? A/DEBUG:     #02 pc 0000000000186100  /data/app/com.google.vr.sdk.samples.videoplayer-jBcNucAD5O9zNL7Fr-Fkeg==/lib/arm64/libgvr.so (Java_com_google_vr_ndk_base_GvrApi_nativeFrameSubmit+116)
03-26 12:10:45.813 32506-32506/? A/DEBUG:     #03 pc 000000000000dbbc  /data/app/com.google.vr.sdk.samples.videoplayer-jBcNucAD5O9zNL7Fr-Fkeg==/oat/arm64/base.odex (offset 0x9000)
03-26 12:10:46.439 769-861/? W/WindowManager: App freeze timeout expired.
03-26 12:10:46.439 769-861/? W/WindowManager: Force clearing freeze: AppWindowToken{ae6b07b token=Token{5f300a ActivityRecord{658c875 u0 com.google.vr.sdk.samples.videoplayer/.WatchVideoActivity t142}}}
03-26 12:10:47.338 769-861/? W/WindowManager: Window freeze timeout expired.
03-26 12:10:47.339 769-861/? W/WindowManager: Force clearing orientation change: Window{16c9c4f u0 com.google.vr.sdk.samples.videoplayer/com.google.vr.sdk.samples.videoplayer.WatchVideoActivity}
03-26 12:10:47.339 769-861/? W/WindowManager: Force clearing orientation change: Window{1c6ecda u0 com.google.android.googlequicksearchbox/com.google.android.launcher.GEL}
03-26 12:10:48.207 588-588/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_01
03-26 12:10:48.210 769-32507/? W/ActivityManager:   Force finishing activity com.google.vr.sdk.samples.videoplayer/.WatchVideoActivity

NEXUS 5X / 8.1.0

**Comment by jdduke** [comment] 2018-03-26 17:00
Hi @dkshin. The VideoPlayer sample is actually only supported on Daydream-ready phones, so it's not unexpected that you're seeing issues on the 5x.

Duplicate of #523.

**Closed by jdduke** 2018-03-26 17:00 UTC
