### ISSUE TITLE
Touch event with VrView

### ISSUE THREAD

**Issue by westlinkin** [googlevr/gvr-android-sdk#133] opened 2016-06-28 09:50 UTC
VrPanoramaView class provides gyro navigation to view panorama. Is it possible to attach touch events along with gyro navigation to the panorama.

**Comment by dav-cz** [comment] 2016-06-28 16:00
Closed as duplicate of https://github.com/googlevr/gvr-android-sdk/issues/132.

Feedback noted!

**Closed by dav-cz** 2016-06-28 16:00 UTC
