### ISSUE TITLE
VrVideoView starts playback in wrong direction.

### ISSUE THREAD

**Issue by smore9982** [googlevr/gvr-android-sdk#180] opened 2016-08-01 15:03 UTC
When I try to play the video below, it starts out facing away speaker. Are there any options in the SDK to specify starting orientation or does this need to come from the video directly? How does the player know which direction to point to when first starting playback?

http://mediadownloads.mlb.com/mlbam/mp4/2016/07/28/980558483/1469724154415/dropf_980558483_100m.mp4

**Comment by dav-cz** [comment] 2016-08-01 21:17
Duplicate of https://github.com/googlevr/gvr-android-sdk/issues/122

**Closed by dav-cz** 2016-08-01 21:17 UTC
