### ISSUE TITLE
setHeadRotation() method For VrWidgetViews (enhancement)

### ISSUE THREAD

**Issue by rneogy** [googlevr/gvr-android-sdk#191] opened 2016-08-05 18:05 UTC
Hi,

I really think it's great that we can now get the head rotation for VrWidgetViews - previously I had to instantiate an extra VrView just to get angles from that one.

However, if I want to direct a user's view towards a specific coordinate or rotation on the panorama, it appears that this is still not an option. Is there a way to do this using the current API? Or can it be implemented into the next version?

Thanks!

**Comment by dav-cz** [comment] 2016-08-05 22:12
Hi, thanks for this feedback. 
The VR View API for the web lets you specify the initial yaw angle, and we're planning to add that to the Android and iOS APIs. 

Would that be sufficient? Or do you really need to be able to set the head rotation at any time? (which can be quite jarring in VR)

**Comment by rneogy** [comment] 2016-08-05 22:50
Hi,

Yeah I think yaw should be plenty enough. Just essentially so that I can set what direction they're looking.

Do you have an estimate of when this feature would be added to Google VR? 

Thanks!

**Comment by dav-cz** [comment] 2016-08-05 23:12
Great, I'll close this bug then since it's a duplicate of [issue 91](https://github.com/googlevr/gvr-android-sdk/issues/91).

In terms of timeline, our next push should be around early September.

**Closed by dav-cz** 2016-08-05 23:12 UTC

**Comment by mjanousek** [comment] 2017-02-01 08:35
Next revision (with setHeadRotation()) haven't been created. Have anyone information about it? When it would be created? @dav-cz ?
Thanks!
