### ISSUE TITLE
VR sample does not play on Samsung devices

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#123] opened 2016-06-21 17:30 UTC
Hi @dav-cz I continued doing device testing at NYTimes and can't get any samsung devices to play the `simplevideowidget` sample.  One example is a S6 running 6.01  I hear audio but the video just shows Pink/Green flashes.  I can include a video if that helps.  Is there something special that needs to be done for the SDK to work with Samsung devices?

**Comment by digitalbuddha** [comment] 2016-06-21 17:36
Additionally on a nexus 5x playing a remote video using the following command:
adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://video1.nytimes.com/video/360-demo/cool.mp4" --ei inputFormat 1

Causes a video that is very laggy. By that I mean the video will play for 1 second then stop audio/video. Few seconds later it will start video/audio again. This is over a 4g connection that has no problems playing other videos (youtube or within NYT app for example)

**Comment by dav-cz** [comment] 2016-06-27 19:37
Hi @digitalbuddha, this (esp. post #1) looks like a duplicate of https://github.com/googlevr/gvr-android-sdk/issues/75 (for which we hope to have a fix!).  So I'm closing this issue.

Could you create a separate issue for post #2 focused on Android N, and ideally tell us 
- if you see this both with mp4 and hls files?
- if you only have this problem with Android N, and not with earlier versions of Android.
Thanks!

**Closed by dav-cz** 2016-06-27 19:37 UTC
