### ISSUE TITLE
How to play ambisonic audio from a video using GvrAudioEngine.createSoundfield?

### ISSUE THREAD

**Issue by xdf103** [googlevr/gvr-android-sdk#156] opened 2016-07-13 05:50 UTC
We are playing a rtmp streaming video. The video stream contains an ambisonic audio. Is it possible to use GvrAudioEngine to play the ambisonic audio? If yes, how to do that?

**Comment by nathanmartz** [comment] 2016-07-13 06:13
Closing as this is a dupe of your other recent questions.

**Closed by nathanmartz** 2016-07-13 06:13 UTC
