### ISSUE TITLE
Cannot move the scene up and down

### ISSUE THREAD

**Issue by barisaraci** [googlevr/gvr-android-sdk#265] opened 2016-10-08 18:06 UTC
Hey, in VrPanoramaView, I cannot move the scene up and down but only right and left. It looks like a common situation, is this a bug?

**Comment by nathanmartz** [comment] 2016-10-08 20:49
It's not a bug but it is a feature we're looking to add. Closing this out as it's already tracked elsewhere here.

**Closed by nathanmartz** 2016-10-08 20:49 UTC

**Comment by solomon2** [comment] 2017-04-15 09:35
@nathanmartz    this feature not has yet ， when you prepare to add?
