### ISSUE TITLE
HeadTracker Drift

### ISSUE THREAD

**Issue by c9iner** [googlevr/gvr-android-sdk#45] opened 2015-12-16 20:47 UTC
We've noticed a significant amount of drift in the head pose returned from HeadTracker.getLastHeadView() on both the Samsung Note4 and S6. The drift is on the order of 5 degrees per second or more.

My guess is that the magnetometer is probably the culprit as it can be easily affected by external magnetic fields, and in my own experience with sensor fusion is the least reliable relative to the gyroscope and accelerometer.

HeadTracker.setGyroBiasEstimationEnabled() is about the only method that seems relevant, but I don't notice much of a difference whether it's on or off.

If there was a way to disable the magnetometer, that would be useful. 

If anyone has other thoughts about the best way to address the drift problem with the existing HeadTracker I would love to hear your thoughts.

**Comment by fcoulombe** [comment] 2015-12-16 20:49
+1

**Comment by koubiak** [comment] 2015-12-17 17:31
Hi,

Thanks Chris for flagging this issue. Drift is something we are working
hard to reduce especially on a device like the note4. Unfortunately it is
not something easy to fix.  The only thing I can say is that we are working
on it, so stay tuned.

As an FYI, the current implementation of the sensor fusion does not use the
magnetometer because of the problem you mentioned.

If you see other problematic devices please let us know.

On Wed, Dec 16, 2015 at 1:10 PM, Francois Coulombe <notifications@github.com

**Comment by andregm3** [comment] 2016-05-24 07:22
check this app has drift solution:

https://play.google.com/store/apps/details?id=org.hitlabnz.sensor_fusion_demo

Open Source:

https://bitbucket.org/apacha/sensor-fusion-demo/

**Comment by R1ck77** [comment] 2016-11-07 01:18
@koubiak Thank you for the explanation. I understand that the Hall sensor has been a source of trouble since Cardboard's inception, but why discard it *now* that you got rid of the magnetic trigger and it could actually be useful? 

I mean, instead of estimating the gyroscope bias, wouldn't make more sense to estimate the compass bias (where integration isn't involved), in order to discard the compass only in the worst case scenarios?

I don't have hard data, but I would say that the drift worsened quite noticeably on my Nexus 5 in the transition from 0.7.0 to 1.0.2. 

I don't have much information yet because I released my update just yesterday, but a One Plus One user noticed the same pattern.

My conjecture is that turning the compass data down is probably going to penalize older models where the accelerometer + gyroscope alone just don't cut it, so it would be probably great to have the compass back, at least conditionally...

@andregm3 the algorithm it's pretty good overall, and it actually relies heavily on the compass (to the point it was unusable with the old cardboard 1.0), but it's not that responsive (which is why I still prefer the Google VR's algorithm, though maybe I'll have to find a way to revert to the old HeadTracker).

**Comment by koubiak** [comment] 2016-11-07 18:00
@R1ck77 Thanks for the pointer. We never used the mag on cardboard for anything else that the trigger detection. We are using mag on daydream ready device with great result (e.g. Pixel / Pixel XL). I am trying to look into the regression you pointed out and try to see why this happens. Thanks a gain for pointed it out.

@andregm3 Our code is designed for VR so it has latency consideration that the code you are pointing out does not have. Otherwise it is an interesting solution.

**Comment by R1ck77** [comment] 2016-11-07 21:21
Thank you, for the support and quick reply: let me know if you need any kind of data or measurement that might help you.

**Comment by ajavamind** [comment] 2016-11-12 19:33
FYI, Using the Samsung S6,  my app built with 0.9.1 SDK did not experience any perceivable drift. When I moved to 1.0.3 there is now a large amount of drift that prevents me from publishing with the latest SDK.

**Comment by koubiak** [comment] 2016-11-13 01:52
Thanks Andy. We will try to investigate the regression.

**Comment by ajavamind** [comment] 2016-11-13 18:00
Also just discovered that with 0.9.1 my app will drift after 20 seconds (with static display/fixture), but by running https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en
a GPS status and calibration app to calibrate, this latent drift problem went away. 
Could these drift issues be resolved with GPS calibration in Viewer settings button function?
thanks!

**Comment by R1ck77** [comment] 2016-11-13 22:13
@ajavamind the Google VR SDK doesn't actually uses the GPS: you can tell by checking the permissions of your app (or the ones of the treasurehunt demo, if you want), where no location-related permission is used (GPS isn't of much use indoor, but we have project Tango to look forward to :) ).

**Comment by ajavamind** [comment] 2016-11-15 02:06
My mistake saying GPS calibration, the app does not have a GPS calibration, it has a pitch/roll and a compass calibration.

**Comment by R1ck77** [comment] 2016-11-15 02:20
I see. 

I have checked the app, but the calibration seems more an "internal to the app" thing to me, than something that might affect the gyro/accelerometer operations system-wide (as far as I know, no Android API to calibrate the sensors exists).

Neither I can't or want to doubt your observations, but unless there is some kind of slim physical/electrical explanation (not a software one), I would be inclined to suspect a fortunate coincidence (but I'm by no means an expert).

**Comment by R1ck77** [comment] 2016-11-19 14:01
Sorry for pestering you, @koubiak, but did you perchance change anything about orientation in the 1.0.3 release?

Because I did a couple of tests (3 in total...) and it seems to be better than the previous one: I'm looking right now at my phone displaying my vr scene on a tripod, and I don't see a noticeable drifting (a couple of degrees every minute at most).

Maybe I'm just making a fool of myself (I'm the first to be aware that this attitude of few and spotty tests not reliable) and I'm just chasing ghosts, otherwise, great job! ;-)

**Comment by koubiak** [comment] 2016-11-21 14:52
Which device are you testing on? This is always a important data point for
us.

Generally we always try to include the latest tweak in our release.

**Comment by R1ck77** [comment] 2016-11-21 14:55
Sorry: still running on Nexus 5.

Thank you for the info!

Il lun 21 nov 2016, 15:52 Pierre Fite-Georgel <notifications@github.com> ha
scritto:

**Comment by jdduke** [comment] 2017-11-29 16:28
HI @R1ck77, are you still seeing this behavior in the latest SDK release? If so, feel free to re-open the issue; a lot has gone into our tracking pipeline in the past year.

**Closed by jdduke** 2017-11-29 16:28 UTC
