### ISSUE TITLE
Controller Emulator crashes immediately after an acceptance of the Bluetooth connection

### ISSUE THREAD

**Issue by Grief** [googlevr/gvr-android-sdk#472] opened 2017-08-31 22:29 UTC
```
W/ContextImpl( 3829): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1235 android.content.ContextWrapper.sendBroadcast:382 com.android.settings.bluetooth.BluetoothSecurityConfirmActivity.onPause:100 android.app.Activity.performPause:5381 android.app.Instrumentation.callActivityOnPause:1239 
V/ActivityManager(  719): Broadcast: Intent { act=android.bluetooth.adapter.action.BLUETOOTH_SECURITY_CONFIRM flg=0x10 (has extras) } ordered=false userid=0 callerApp=ProcessRecord{42990378 3829:com.android.settings/1000}
W/ActivityManager(  719): Duplicate finish request for ActivityRecord{4355fc88 u0 com.android.settings/.bluetooth.BluetoothSecurityConfirmActivity t28 f}
D/BluetoothAdapterService( 1719): onReceive()
D/ActivityThread( 3829): ACT-AM_ON_PAUSE_CALLED ActivityRecord{43636c80 token=android.os.BinderProxy@42cec990 {com.android.settings/com.android.settings.bluetooth.BluetoothSecurityConfirmActivity}}
D/BluetoothAdapterService( 1719): onReceive(), Handle ACTION_USER_CONFIRM, WaitForConfirmation: false, result: 0
D/Reduce_FPS(  719): [ Reduce FPS ][ ActivityManager ] :: completePauseLocked, restore1 FPS to 60, processName: com.android.settings
D/Reduce_FPS(  719): [ Reduce FPS ][ Choreographer ] :: setVsyncType, normal: true
I/libPerfService(  719): 1: set: 2
E/        (  719): Could not open '/data/data/hotplug/cmd'
E/        (  719): error : 2, No such file or directory
W/hwcomposer(  147): [COMP] (0:3) FBT might use ION (handle=0xb7eb5fb8)
W/ContextImpl(  719): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1235 com.android.server.wm.WindowManagerService.updateOrientationFromAppTokens:4089 com.android.server.am.ActivityStack.resumeTopActivityLocked:1681 com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked:2350 com.android.server.am.ActivityStack.completePauseLocked:989 
V/ActivityManager(  719): Broadcast: Intent { act=android.intent.action.WINDOW_MANAGER_SERVICE_FORCED_APP_ORIENTATION flg=0x10 (has extras) } ordered=false userid=0 callerApp=ProcessRecord{42a33620 719:system/1000}
D/InputReader(  719): InputReader:: getSwitchState lock 
D/InputReader(  719): InputReader::getStateLocked:: return 
I/ActivityManager(  719): boardcastResumedActivityInfo: start ...packageName:com.google.vr.inputcompanion
V/ActivityManager(  719): Broadcast: Intent { act=action.boardcast.resume.activity.info flg=0x10 (has extras) } ordered=false userid=-2 callerApp=ProcessRecord{42a33620 719:system/1000}
V/WindowManager(  719): Changing focus from Window{429f9610 u0 com.android.settings/com.android.settings.bluetooth.BluetoothSecurityConfirmActivity} to Window{432d6148 u0 com.google.vr.inputcompanion/com.google.vr.inputcompanion.MainActivity} Callers=com.android.server.wm.WindowManagerService.handleAppTransitionReadyLocked:9431 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:9985 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:8908 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked:8850 
D/PhoneStatusBar(  881): setSystemUiVisibility(vis: 0x1700, mask: 0xffffffff)
D/PhoneStatusBar(  881): setSystemUiVisibility---->oldVal=10000, newVal=1700, diff: 71424
D/PhoneStatusBar(  881): disable: 0x00010000 -> 0x00000000 (diff: 0x00010000)
D/PhoneStatusBar(  881): disable: < expand* icons alerts ticker system_info back home recent clock search >
D/PhoneStatusBar(  881): hiding the MENU button
I/WindowManager(  719): Gaining focus: Window{432d6148 u0 com.google.vr.inputcompanion/com.google.vr.inputcompanion.MainActivity}
I/WindowManager(  719): Losing focus: Window{429f9610 u0 com.android.settings/com.android.settings.bluetooth.BluetoothSecurityConfirmActivity}
D/dalvikvm(  719): create interp thread : stack size=128KB
D/dalvikvm(  719): create new thread
D/dalvikvm(  719): new thread created
D/dalvikvm(  719): update thread list
D/dalvikvm(  719): threadid=80: interp stack at 0x65698000
D/dalvikvm(  719): init ref table
D/dalvikvm(  719): init mutex
D/dalvikvm(  719): threadid=80: created from interp
D/dalvikvm(  719): start new thread
D/dalvikvm(  719): threadid=80: notify debugger
D/dalvikvm(  719): threadid=80 (Thread-280): calling run()
D/ActivityThread( 3829): ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@42cec990
D/dalvikvm(  719): threadid=80: exiting
D/dalvikvm(  719): threadid=80: bye!
D/LenovoPowerMonitor(  719): mBroadcastReceiver.onReceive,action:action.boardcast.resume.activity.info
V/LenovoPowerMonitor(  719): package changed: current package:com.google.vr.inputcompanion
D/SmartRotationService( 1484): onReceive  action =  android.intent.action.WINDOW_MANAGER_SERVICE_FORCED_APP_ORIENTATION
D/SmartRotationService( 1484): Receive WINDOW_MANAGER_SERVICE_FORCED_APP_ORIENTATION forced_app_orientation_data= 1
D/bluewind( 1452): 11111 action:action.boardcast.resume.activity.info
D/bluewind( 1452): open new application ------ packageName:com.google.vr.inputcompanion
D/bluewind( 1452): top package name:com.android.settings
D/Hwmsen_sensors(  719): active_sensors =19
D/SensorService(  719):         >>> actuating h/w setDelay 0 1000000 
D/Accel   (  719): setDelay: (handle=0, ns=1000000)
D/Accel   (  719): no ACC setDelay control attr 
E/Sensors (  719): new acc setDelay handle(0),ns(1000000) err! go to hwmsen
D/Hwmsen_sensors(  719): setDelay: (handle=0, ns=1000000)
D/Hwmsen_sensors(  719): setDelay: (what=0, ms=1)
D/Hwmsen_sensors(  719): Control set delay 1 ms is too small 
D/Hwmsen_sensors(  719): really setDelay: (what=0, ms=10)
D/SensorManager(10449): enableSensor: BMA056 3-axis Accelerometer
E/SensorManager(10449): sensor or listener is null
D/SensorService(  719): Calling batch handle==3 flags=0 rate=0 timeout== 0
D/SensorService(  719): SensorDevice::batch: ident=0x6825e188, handle=0x00000003, flags=0, period_ns=1000000 timeout=0
D/SensorService(  719):         >>> curr_period=1000000 min_period=1000000 curr_timeout=0 min_timeout=0
D/SensorService(  719): Calling activate on 3
D/SensorService(  719): SensorDevice::activate: ident=0x6825e188, handle=0x00000003, enabled=1, count=2
D/SensorService(  719): enable index=1
D/SensorService(  719):         >>> actuating h/w setDelay 3 1000000 
E/Sensors (  719): new acc setDelay handle(3),ns(1000000) err! go to hwmsen
D/Hwmsen_sensors(  719): setDelay: (handle=3, ns=1000000)
D/Hwmsen_sensors(  719): setDelay: (what=3, ms=1)
D/Hwmsen_sensors(  719): Control set delay 1 ms is too small 
D/Hwmsen_sensors(  719): really setDelay: (what=3, ms=10)
D/SensorManager(10449): enableSensor: BMM056 software  gyroscope Sensor
D/SensorService(  719): Calling batch handle==0 flags=0 rate=0 timeout== 0
D/SensorService(  719): SensorDevice::batch: ident=0x6825e188, handle=0x00000000, flags=0, period_ns=1000000 timeout=0
D/SensorService(  719):         >>> curr_period=1000000 min_period=1000000 curr_timeout=0 min_timeout=0
D/SensorService(  719): Calling activate on 0
D/SensorService(  719): SensorDevice::activate: ident=0x6825e188, handle=0x00000000, enabled=1, count=2
D/SensorService(  719): enable index=1
D/SensorService(  719):         >>> actuating h/w setDelay 0 1000000 
D/Accel   (  719): setDelay: (handle=0, ns=1000000)
D/Accel   (  719): no ACC setDelay control attr 
E/Sensors (  719): new acc setDelay handle(0),ns(1000000) err! go to hwmsen
D/Hwmsen_sensors(  719): setDelay: (handle=0, ns=1000000)
D/Hwmsen_sensors(  719): setDelay: (what=0, ms=1)
D/Hwmsen_sensors(  719): Control set delay 1 ms is too small 
D/Hwmsen_sensors(  719): really setDelay: (what=0, ms=10)
D/SensorManager(10449): enableSensor: BMA056 3-axis Accelerometer
E/HoverComponent(10449): Unable to create a HoverHeatmapProvider.
D/dalvikvm(10449): create interp thread : stack size=128KB
D/dalvikvm(10449): create new thread
D/dalvikvm(10449): new thread created
D/dalvikvm(10449): update thread list
D/dalvikvm(10449): threadid=14: interp stack at 0x622f9000
D/dalvikvm(10449): init ref table
D/dalvikvm(10449): init mutex
D/dalvikvm(10449): threadid=14: created from interp
D/dalvikvm(10449): start new thread
D/dalvikvm(10449): threadid=14: notify debugger
I/BluetoothSocketServer(10449): Bluetooth server socket stopped.
D/dalvikvm(10449): threadid=14 (Read Thread): calling run()
D/dalvikvm(10449): threadid=12: exiting
I/InputCompanionServer(10449): Read thread started
D/dalvikvm(10449): threadid=12: bye!
D/BluetoothSocket(10449): close() in, this: android.bluetooth.BluetoothSocket@428e2630, channel: 24, state: CONNECTED
D/BluetoothSocket(10449): read in:  android.net.LocalSocketImpl$SocketInputStream@428e2b10 len: 4
D/BluetoothSocket(10449): close() this: android.bluetooth.BluetoothSocket@428e2630, channel: 24, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@428e2b10, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@428e2b20mSocket: android.net.LocalSocket@428e2a70 impl:android.net.LocalSocketImpl@428e2a98 fd:FileDescriptor[66]
D/BluetoothSocket(10449): Closing mSocket: android.net.LocalSocket@428e2a70 impl:android.net.LocalSocketImpl@428e2a98 fd:FileDescriptor[66]
I/        (  168): [session]POLLHUP: 10, POLLRDHUP: 2000, POLLERR:  8, POLLNVAL: 20
E/        (  168): [session]revert_socket_event: 2011
I/MTKBT   (  168): [Session]process_session_event 2
I/MTKBT   (  168): [session]update_event: session id[44], event[0x   6]
I/MTKBT   (  168): [session]update_event: session event[0]
I/MTKBT   (  168): [Session]process_session_event end
I/MTKBT   (  168): [session]reorganize_sessions
I/MTKBT   (  168): [session]garbage session[44][1719]
I/MTKBT   (  168): [Session]session_read: name [bt.session.default], id[44], subid[1719], size[15839]
I/MTKBT   (  168): [session]close fd[31]
E/MTKBT   (  168): [Session]find no session to read
I/MTKBT   (  168): [Session]retrieve_fds_monitored 64
E/MTKBT   (  168): [Session]no first session in list
I/MTKBT   (  168): [Session]session_destroy: name [bt.session.default], id[44], subid[1719]
E/MTKBT   (  168): [Session]find no session to destroy
D/BluetoothSocket(10449): close() in, this: android.bluetooth.BluetoothSocket@428e2630, channel: 24, state: CLOSED
W/System.err(10449): java.io.IOException: bt socket closed, read return: -1
D/BluetoothSocket(10449): close() in, this: android.bluetooth.BluetoothSocket@428e2630, channel: 24, state: CLOSED
D/dalvikvm(10449): threadid=11: exiting
D/dalvikvm(10449): threadid=11: bye!
I/BluetoothSocketServer(10449): Stopped bluetooth socket server.
D/ActivityThread(10449): ACT-AM_ON_PAUSE_CALLED ActivityRecord{427f1b08 token=android.os.BinderProxy@427f0918 {com.google.vr.inputcompanion/com.google.vr.inputcompanion.MainActivity}}
D/ActivityThread(10449): ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@427f0918
V/ActivityThread(10449): Finishing stop of ActivityRecord{427f1b08 token=android.os.BinderProxy@427f0918 {com.google.vr.inputcompanion/com.google.vr.inputcompanion.MainActivity}}: show=true win=com.android.internal.policy.impl.PhoneWindow@428049c8
D/ActivityThread(10449): ACT-STOP_ACTIVITY_SHOW handled : 0 / android.os.BinderProxy@427f0918
D/AndroidRuntime(10449): Shutting down VM
W/dalvikvm(10449): threadid=1: thread exiting with uncaught exception (group=0x41a88c98)
W/dalvikvm(10449): threadid=1: uncaught exception occurred
W/System.err(10449): java.lang.NullPointerException
D/OpenGLRenderer( 3829): Flushing caches (mode 0)
W/System.err(10449):    at com.google.vr.inputcompanion.MainActivity$9$1.run(MainActivity.java:300)
W/System.err(10449):    at android.os.Handler.handleCallback(Handler.java:808)
W/System.err(10449):    at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(10449):    at android.os.Looper.loop(Looper.java:193)
W/System.err(10449):    at android.app.ActivityThread.main(ActivityThread.java:5395)
W/System.err(10449):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(10449):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(10449):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
W/System.err(10449):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
W/System.err(10449):    at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(10449): threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime(10449): FATAL EXCEPTION: main
E/AndroidRuntime(10449): Process: com.google.vr.inputcompanion, PID: 10449
E/AndroidRuntime(10449): java.lang.NullPointerException
E/AndroidRuntime(10449):        at com.google.vr.inputcompanion.MainActivity$9$1.run(MainActivity.java:300)
E/AndroidRuntime(10449):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(10449):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(10449):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(10449):        at android.app.ActivityThread.main(ActivityThread.java:5395)
E/AndroidRuntime(10449):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10449):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10449):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/AndroidRuntime(10449):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
E/AndroidRuntime(10449):        at dalvik.system.NativeStart.main(Native Method)
V/SettingsProvider(  719): call(global:dropbox:data_app_crash) for 0
D/SettingsProvider(  719): lookupValue table global cache.fullyMatchesDisk() dropbox:data_app_crash
D/dalvikvm(  719): create interp thread : stack size=128KB
D/dalvikvm(  719): create new thread
D/dalvikvm(  719): new thread created
D/dalvikvm(  719): update thread list
D/dalvikvm(  719): threadid=80: interp stack at 0x65698000
D/dalvikvm(  719): init ref table
D/dalvikvm(  719): init mutex
D/dalvikvm(  719): threadid=80: created from interp
D/dalvikvm(  719): start new thread
D/dalvikvm(  719): threadid=80: notify debugger
D/dalvikvm(  719): threadid=80 (Error dump: data_app_crash): calling run()
```

**Comment by jdduke** [comment] 2017-11-13 16:47
Duplicate of issue #484

**Closed by jdduke** 2017-11-13 16:47 UTC

**Comment by Grief** [comment] 2017-11-13 18:24
@jdduke it was opened earlier than #484 but whatever
