### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by s1mar** [googlevr/gvr-android-sdk#238] opened 2016-09-15 10:15 UTC
After upgrading the project gradle plugin and/or adding more libraries,the VRPanoramaView just doesnt work,always gives this error 

`FATAL EXCEPTION: main
                                                                    Process: com.ns.simarjot.arch, PID: 2543
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ns.simarjot.arch/com.ns.simarjot.arch.TestActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                     Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                        at com.ns.simarjot.arch.TestActivity.onCreate(TestActivity.java:26)
                                                                        at android.app.Activity.performCreate(Activity.java:6237)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                        at com.ns.simarjot.arch.TestActivity.onCreate(TestActivity.java:26) 
                                                                        at android.app.Activity.performCreate(Activity.java:6237) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                        at com.ns.simarjot.arch.TestActivity.onCreate(TestActivity.java:26) 
                                                                        at android.app.Activity.performCreate(Activity.java:6237) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                     Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-support-annotations-24.1.1_062ad37633a99321e6a59b7344ab769e17e3db55-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.ns.simarjot.arch/files/instant-run/dex/slice-slice_3-classes.dex", dex file`

**Comment by sigmaxipi** [comment] 2016-09-16 03:48
The Realm.io library has native code for multiple architectures. If you unzip the apk that is crashing, you'll probably see a arm+arm64 libraries from Realm and only arm libraries from GVR. If so, you're running into a variation of https://github.com/googlevr/gvr-android-sdk/issues/38 and will need to follow the directions at https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native to resolve it.

**Comment by s1mar** [comment] 2016-09-19 09:04
I added this to my app gradle build file:

First this,ndk { abiFilters "armeabi-v7a" } and the app started running on my device which is a one plus 2 but still refused to run on my other test device,which is a Sony M4 pro Aqua.

So,then I added packagingOptions { exclude "lib/arm64-v8a/librealm-jni.so" }

to my build.gradle file,the app still runs fine on my phone but on the other device it gives weird erros like unable to locate the global application code file and what not.
Now,the one plus 2 has a combination of A57 and A53 cores whereas the other uses 4 A53 cores, but both use the same armv8 instruction set,so I am confused now what's causing it to run on some devices and not on others

**Comment by sigmaxipi** [comment] 2016-09-25 02:00
What is the exact error message? Can you run `adb logcat -c`, run the app, and then run `adb logcat` to get the full crash logs?

**Comment by kneth** [comment] 2016-09-29 14:13
@s1mar @sigmaxipi I have written a minimal app and cannot reproduce it: https://github.com/realm/realm-java/issues/3441

**Comment by sigmaxipi** [comment] 2016-09-30 05:47
With the latest SDK, the .aars have arm, arm64, and x86 binaries built in. This might prevent this class of issues caused by using the GVR SDK with other native libraries.

**Comment by s1mar** [comment] 2016-09-30 06:07
I'll try the latest sdk v1.0.0 and let you know

**Comment by acrive82** [comment] 2016-09-30 15:54
Also, remeber to set proguard rules

`# Don't obfuscate any NDK/SDK code. This makes the debugging of stack traces in
# in release builds easier.
-keepnames class com.google.vr.ndk.** { *; }
-keepnames class com.google.vr.sdk.** { *; }

# These are part of the SDK <-> VrCore interfaces for GVR.
-keepnames class com.google.vr.vrcore.library.api.** { *; }

# These are part of the Java <-> native interfaces for GVR.
-keep class com.google.vr.** { native <methods>; }

-keep class com.google.vr.cardboard.annotations.UsedByNative
-keep @com.google.vr.cardboard.annotations.UsedByNative class *
-keepclassmembers class * {
    @com.google.vr.cardboard.annotations.UsedByNative *;
}

-keep class com.google.vr.cardboard.UsedByNative
-keep @com.google.vr.cardboard.UsedByNative class *
-keepclassmembers class * {
    @com.google.vr.cardboard.UsedByNative *;
}
`

**Comment by dav-cz** [comment] 2016-11-01 21:15
Thanks all for helping on this! 
Closing the issue as it should work with the latest sdk. Please re-open if that's not the case.

**Closed by dav-cz** 2016-11-01 21:15 UTC
