### ISSUE TITLE
ndk-controllerpaint doesn't run properly

### ISSUE THREAD

**Issue by mattscar** [googlevr/gvr-android-sdk#326] opened 2016-12-25 01:29 UTC
After I updated Google VR Services on my Google Pixel, the ndk-controllerpaint app won't run properly. I can compile and deploy the code, but I get the "Place your phone into the headset" screen followed by the controller test screen, over and over again. The application's screen never appears.

Also, in AndroidManifest.xml, the application's label is set to "MainActivity". That's not really a descriptive name.

**Comment by jdduke** [comment] 2017-01-03 16:18
>  I get the "Place your phone into the headset" screen followed by the controller test screen, over and over again. The application's screen never appears.

Are you using a Daydream View headset+controller? What happens after you complete the controller calibration step? A bug report or the logcat would be helpful, thanks.

**Comment by mattscar** [comment] 2017-01-03 20:24
Hi,

Yes, I have a Daydream headset and controller. After inserting the phone into the headset and completing the controller calibration, the window returns to the "Insert device into headset" screen. It repeats this loop (calibration and insert device) repeatedly.

This problem started after I updated the Google VR Services on my Google Pixel. I copied the LogCat output to a text file and removed every line not containing "vr" or "controller".

Thanks,
Matt
[logcat_vr.txt](https://github.com/googlevr/gvr-android-sdk/files/683153/logcat_vr.txt)

**Comment by jdduke** [comment] 2017-01-03 22:10
Yeah, those logs are a bit puzzling, it's as if VrCore fails to persist the active VR state, which causes the ControllerPaint to continually re-trigger the VR entry flow when resumed.

Are you only seeing this issue when you deploy the app from Android Studio? Can you repro when launching the sample directly from Android's launcher? or from within VR via the Daydream app launcher? Do any other Daydream apps exhibit this issue on your device? You might try clearing "Google VR Services" app data/cache. I haven't been able to repro locally so far, but I haven't tried deploying directly from Android Studio.

**Comment by mattscar** [comment] 2017-01-03 22:21
I cleared the data/cache for Google VR Services and ran the sample from the Android launcher, I got the same looping problem as before.

But when I ran the sample from inside the Daydream environment, it worked fine.

**Comment by jdduke** [comment] 2017-01-03 22:42
OK, thanks for the update. Do you have the same issue with the TreasureHunt sample? Or is it just ControllerPaint? Apologies for asking so many questions, just trying to diagnose the problem.

**Comment by mattscar** [comment] 2017-01-04 12:50
Yes, I encounter the same problem with the TreasureHunt sample.

I've found a way to fix the problem. In the project's manifest, the android:theme attribute is set to "@style/VrActivityTheme". When I remove the attribute from <application>, the app works fine.

The project's res folder doesn't contain any style resources. Is "VrActivityTheme" supposed to be provided by the Google VR Service?

**Comment by jdduke** [comment] 2017-01-04 16:12
VrActivityTheme is defined in [common.aar](https://github.com/googlevr/gvr-android-sdk/blob/master/libraries/sdk-common-1.10.0.aar). It's not clear why your project would fail to find this at runtime, assuming it's including the correct common.aar library (though I didn't see a resource failure in your logcat, maybe there was a runtime exception getting stripped out?).

@sigmaxipi any ideas?

**Comment by mattscar** [comment] 2017-01-04 17:50
Judging from the module's build.gradle file, it looks like the only AAR included in the build is the base library:

dependencies {
    compile 'com.google.vr:sdk-base:1.10.0'
}

**Comment by jdduke** [comment] 2017-01-04 22:36
If you add:

compile 'com.google.vr:sdk-common1.10.0'

to the dependencies, does that resolve the problem?

**Comment by jdduke** [comment] 2017-01-04 22:36
Woops, that should have been

`compile 'com.google.vr:sdk-common:1.10.0'`

**Comment by 411Productions** [comment] 2017-01-04 22:45
Unsubscribe


Michael Zyda, Director
USC GamePipe Laboratory
746 West Adams, EGG Building
Los Angeles, CA 90089-7725
Zyda@usc.edu<mailto:Zyda@usc.edu>
310-463-5774
310-496-0557 Fax

On Jan 4, 2017, at 2:36 PM, Jared Duke <notifications@github.com<mailto:notifications@github.com>> wrote:


If you add:

compile 'com.google.vr:sdk-common1.10.0'

to the dependencies, does that resolve the problem?

**Comment by mattscar** [comment] 2017-01-04 22:54
No it doesn't. I wondered how the project could compile without a definition for @style/VrActivityTheme. I did some searching, and base.aar has its own definition that's exactly the same as the one in common.aar. Here's what it looks like:

<style name="VrActivityTheme" parent="@android:style/Theme.Black.NoTitleBar">
<item name="android:windowFullscreen">true</item>
<item name="android:windowAnimationStyle">@null</item>
<item name="android:windowActionBar">false</item>
<item name="android:windowDisablePreview">true</item>
<item name="android:windowContentOverlay">@null</item>
</style>

I think one of these attributes is preventing the app from running properly (at least on my system). I'll do some tests and report back.

**Comment by mattscar** [comment] 2017-01-04 23:13
The app worked fine after I removed the `android:windowDisablePreview` item. That is, I removed the following line from the `VrActivityTheme` definition:

`<item name="android:windowDisablePreview">true</item>`

**Comment by jdduke** [comment] 2017-01-05 01:22
Interesting, though I'm still unable to reproduce the issue.  Just to confirm, you're using a stock Google Pixel? With Android 7.1? Could you share the build number (Settings -> About phone -> Build number).  And you're not running any background utility/third-party apps that try to evict processes/Activities or manage memory/CPU? And you haven't enabled the "Don't keep activities" settings in Android developer options?

The fact that base.aar includes those resources is actually an oversight (thanks for pointing that out!), and should be resolved in the next SDK push. However, it's not clear why removing the windowDisablePreview attribute from the style would resolve the issue you're seeing.

**Comment by mattscar** [comment] 2017-01-05 03:59
I'm using a stock Google Pixel running Android 7.1.1. Build number NMF260.

I did have the "Don't keep activities" setting enabled. After I disabled that, my issues went away. 

I guess everything's cleared up. Sorry for all the bother.

**Comment by jdduke** [comment] 2017-01-05 04:10
No worries, thanks for your patience in debugging the issue. I suspect enabling the "Don't keep activities" confuses our bookkeeping for the active VR app, which causes the repeating VR entry screen loop. Regardless, it's good to know what the symptoms here look like, I'll see if there's anything else we should be doing on our end to properly handle this case. Cheers.

**Closed by jdduke** 2017-01-05 04:10 UTC
